### ISSUE TITLE
"NoneType" error when looping over all networks and trying to get the stations

### ISSUE THREAD

**Issue by Altonss** [eskerda/python-citybikes#7]
I wanted to try and read the stations of all networks, but in the for loop over the networks, I get at some point (and often at another network) a NoneType error (network.stations is of type NoneType)... Is there some kind of rate limit in the API that could be causing this issue or what could this be related to?

**Comment by Altonss** [comment]
Adding a time.sleep(0.25) between each network fixes the issue somehow...

**Comment by eskerda** [comment]
It's a rate limit error
